version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo/db:/data/db # /data/db是container中存放数据位置
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    links:
      - mongo # 这里关联mongo的container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: kwong
      ME_CONFIG_BASICAUTH_PASSWORD: kwong123

  redis:
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisdb/:/data/
  # nginx:
  #   image: nginx:latest
  #   # container_name: nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ${NGINX_CONFIG}:/etc/nginx/conf.d
  #     - ${NGINX_LOGS}:/var/log/nginx
  #     - ${CODE_DIR}:/var/www/html
  #   restart: always
